node{
  stage('SCM Checkout'){
    git 'https://github.com/RamakrishnaPatil/jenkins/test'
  }
  stage('Compile-Package'){
    def mvnHome = tool name: 'Macen 3.6.3', type: 'maven'
    sh "${mvnHome}/bin/mvn package"
  }
}
